blank_issues_enabled: true
contact_links:
  - name: Codidact Community Forum
    url: https://forum.codidact.org/
    about: Please ask and answer questions here.
  - name: Codidact Discord Server
    url: https://discord.gg/WZ7aTst
    about: Join us on Discord for more on-the-go discussion.
  - name: Codidact Project Wiki
    url: https://github.com/codidact/docs/wiki
    about: For more in-depth information please use our wiki.
